### ISSUE TITLE
Publish this VSCode extension also in open-vsx.org

### ISSUE THREAD

**Issue by elgalu** [mgesbert/vscode-python-path#12]
Would it be possible that you publish this VSCode extension also in https://open-vsx.org/

This would make it much easier to use the extension in project such as

* [gitpod.io](https://gitpod.io/)
* [theia-ide.org](https://theia-ide.org/)
* [VS Codium](https://vscodium.com/)
* [code-server](https://github.com/cdr/code-server)

thanks in advance

**Comment by mgesbert** [comment]
Hello, I'll look into it and I'll keep you posted

**Comment by mgesbert** [comment]
It's done, I hope people find it useful 🙂
